'use strict';
(()=>{
const $=id=>document.getElementById(id), api=window.crew;
let state={connected:false,busy:false,messages:[]}, assistant=null, entered=false, approvalQueue=[], pendingApproval=null;
const providerInfo={codex:['Connect with ChatGPT','Sign in through Codex in your browser. Uses your eligible ChatGPT plan and its usage limits.'],claude:['Connect Claude','Connect your Anthropic API account. Claude chat subscriptions do not cover API usage.'],gemini:['Connect Gemini','Connect your Google AI Studio API account. API quotas and any charges apply.']};
function notice(text){$('setupStatus').textContent=text||'';}
function busyUI(){const busy=!!state.busy;$('send').disabled=busy||!state.connected||!state.project||!entered;$('stop').hidden=!busy;$('settings').disabled=busy;$('runState').textContent=busy?'Working':'Idle';$('worldStatus').textContent=busy?'Live work · following AI activity':'Ambient life · no work running';$('activityDot').textContent=busy?'●':'○';}
function renderState(next,history=false){if(!next)return;state={...state,...next};if(state.connected)state.authPending=false;if(state.project){const path=typeof state.project==='string'?state.project:state.project.path||state.project.root||state.project.name||'';$('projectPath').textContent=path;$('projectName').textContent=path.split(/[\\/]/).filter(Boolean).pop()||'Local project';$('projectName').title=path;}else{$('projectPath').textContent='No project selected';$('projectName').textContent='Choose a project';}if(state.provider)$('provider').value=state.provider;$('providerBadge').textContent=state.connected?({codex:'Codex · ChatGPT',claude:'Claude API',gemini:'Gemini API'}[state.provider]||state.provider)+' connected':'Not connected';$('enter').disabled=!state.project||!state.connected;const models=state.models||[];$('modelGroup').hidden=!models.length;if(models.length){const chosen=state.model||$('model').value;$('model').replaceChildren(...models.map(m=>{const option=document.createElement('option');option.value=m.id||m.model;option.textContent=m.name||m.displayName||m.id||m.model;return option;}));if(models.some(m=>(m.id||m.model)===chosen))$('model').value=chosen;$('modelGroup').hidden=false;}if(history){$('messages').replaceChildren();assistant=null;for(const m of state.messages||[])addMessage(m.role,m.text||m.content||'');if(!$('messages').children.length)empty();}busyUI();}
function empty(){$('messages').replaceChildren();const el=document.createElement('div');el.className='empty-chat';const h=document.createElement('h3');h.textContent='Give the day a purpose.';const p=document.createElement('p');p.textContent='Ask a question or send a mission. Your connected AI does the work; the town makes it visible.';el.append(h,p);$('messages').append(el);}
function bottom(){$('messages').scrollTop=$('messages').scrollHeight;}
function addMessage(role,text){$('messages').querySelector('.empty-chat')?.remove();const wrap=document.createElement('article');wrap.className='message '+role;const label=document.createElement('small');label.textContent=role==='user'?'YOU':role==='error'?'CONNECTION NOTICE':'THE CREW';const body=document.createElement('div');body.className='body';body.textContent=String(text);wrap.append(label,body);$('messages').append(wrap);bottom();return body;}
function providerChanged(){$('keyGroup').hidden=$('provider').value==='codex';$('connect').textContent=providerInfo[$('provider').value][0];$('providerHelp').textContent=providerInfo[$('provider').value][1];$('modelGroup').hidden=$('provider').value!==state.provider||!(state.models||[]).length;$('enter').disabled=!state.project||!state.connected||$('provider').value!==state.provider;notice('');}
async function call(button,fn){button.disabled=true;try{return await fn();}catch(e){notice(e.message||String(e));return null;}finally{button.disabled=false;busyUI();}}
function showSetup(){if(!$('setup').open)$('setup').showModal();$('closeSetup').hidden=!entered;providerChanged();}
$('settings').onclick=showSetup;$('closeSetup').onclick=()=>$('setup').close();$('setup').addEventListener('cancel',e=>{if(!entered)e.preventDefault();});
$('chooseProject').onclick=()=>call($('chooseProject'),async()=>{const next=await api.chooseProject();if(next?.project!==state.project){entered=false;$('closeSetup').hidden=true;}renderState(next,true);notice('Project selected.');});
$('createProject').onclick=()=>call($('createProject'),async()=>{const next=await api.createProject();if(next?.project!==state.project){entered=false;$('closeSetup').hidden=true;}renderState(next,true);notice('Project ready.');});
$('provider').onchange=providerChanged;
$('connect').onclick=()=>call($('connect'),async()=>{notice('Connecting…');entered=false;$('closeSetup').hidden=true;const provider=$('provider').value,key=$('apiKey').value.trim();const next=await api.connect({provider,apiKey:key||undefined,model:$('model').value||undefined});$('apiKey').value='';renderState(next,true);notice(next?.authPending?'Finish signing in in your browser. This window will update automatically.':next?.connected?'Connected. Choose project access and enter the world.':'Connection not ready yet.');});
$('enter').onclick=()=>call($('enter'),async()=>{const mode=$('mode').value;notice('Opening your project…');const next=await api.enter({model:$('model').value||undefined,mode});renderState(next,true);entered=true;$('mode').value=next.mode||mode;$('modeBadge').textContent=(next.mode||mode)==='read-only'?'Read only':'Project work';$('setup').close();window.world.fit();$('prompt').focus();});
$('composer').onsubmit=async e=>{e.preventDefault();const text=$('prompt').value.trim();if(!text||state.busy)return;addMessage('user',text);$('prompt').value='';assistant=null;state.busy=true;busyUI();try{await api.send({text});}catch(error){addMessage('error',error.message||String(error));state.busy=false;busyUI();window.world.done();}};
$('prompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();$('composer').requestSubmit();}};
$('stop').onclick=async()=>{try{$('stop').disabled=true;await api.stop();}catch(e){addMessage('error',e.message);}finally{$('stop').disabled=false;}};$('clearView').onclick=bottom;
function showApproval(){if(pendingApproval||!approvalQueue.length)return;pendingApproval=approvalQueue.shift();$('approvalTitle').textContent=pendingApproval.title||'Allow this action?';$('approvalDetail').textContent=typeof pendingApproval.detail==='string'?pendingApproval.detail:JSON.stringify(pendingApproval.detail||{},null,2);$('approval').showModal();}
async function approve(allow){if(!pendingApproval)return;const id=pendingApproval.id;$('allow').disabled=$('deny').disabled=true;try{await api.approve({id,allow});pendingApproval=null;$('approval').close();showApproval();}catch(e){$('approvalDetail').textContent+='\n\n'+e.message;}finally{$('allow').disabled=$('deny').disabled=false;}}
$('allow').onclick=()=>approve(true);$('deny').onclick=()=>approve(false);$('approval').addEventListener('cancel',e=>{e.preventDefault();approve(false);});
function event(e){if(!e)return;if(e.type==='status'){renderState(e.status&&typeof e.status==='object'?e.status:e);if(state.connected)notice('Connected. You can enter the world.');else if(state.authPending)notice('Finish signing in in your browser, then return here.');else notice('Not connected. Choose a provider and connect to continue.');}else if(e.type==='text'){if(!assistant)assistant=addMessage('assistant','');assistant.textContent+=e.text||'';bottom();}else if(e.type==='activity'){window.world.activity(e);$('activityText').textContent=e.text||'Working';}else if(e.type==='done'){state.busy=false;assistant=null;busyUI();window.world.done();$('activityText').textContent=e.status==='failed'?'Work stopped with an error.':e.status==='cancelled'||e.status==='interrupted'?'Stopped by you.':'Turn finished. See the conversation for results.';approvalQueue=[];pendingApproval=null;$('approval').close();}else if(e.type==='error'){addMessage('error',e.message||'The connection reported an error.');notice(e.message);}else if(e.type==='approval'){approvalQueue.push(e);showApproval();}}
window.crewUIDiagnostics=()=>({setupOpen:$('setup').open,connected:state.connected,busy:state.busy,project:!!state.project,messages:$('messages').querySelectorAll('.message').length,noPageOverflow:document.documentElement.scrollHeight<=innerHeight,sidebarFits:document.querySelector('aside').scrollHeight<=document.querySelector('aside').clientHeight,composerVisible:$('composer').getBoundingClientRect().bottom<=innerHeight});
if(!api){notice('The desktop connection is unavailable. Open the app through its launcher.');showSetup();return;}api.onEvent(event);api.status().then(s=>{renderState(s,true);showSetup();}).catch(e=>{showSetup();notice(e.message);});
})();
